vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        upload:
            uri_prefix: /asset/images
            upload_destination: '%kernel.project_dir%/public/asset/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
